// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "capivARa",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "capivARa",
            targets: ["AppModule"],
            bundleIdentifier: "br.ufpe.cin.jvlm2.capivARa",
            teamIdentifier: "ZCQ4VSC547",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.mint),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "WE need to acces the camera to enable the AR session")
            ],
            appCategory: .education
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Audios")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)
